export interface AyurvedicInfo {
  scientificName: string;
  localNames: { hindi?: string; sanskrit?: string; tamil?: string; telugu?: string; kannada?: string; marathi?: string };
  medicinalUses: string[];
  ayurvedicBenefits: string[];
  doshaEffect?: string;
  partUsed?: string;
}

const DB: AyurvedicInfo[] = [
  { scientificName: "Ocimum tenuiflorum", localNames: { hindi: "Tulsi", sanskrit: "Surasa" }, medicinalUses: ["Cough & cold relief", "Fever reducer", "Anti-inflammatory", "Immunity booster"], ayurvedicBenefits: ["Balances Kapha & Vata", "Purifies blood", "Supports respiratory health", "Adaptogenic — reduces stress"], doshaEffect: "Balances Kapha & Vata", partUsed: "Leaves, seeds" },
  { scientificName: "Ocimum basilicum", localNames: { hindi: "Tulsi / Babui Tulsi", sanskrit: "Surasa" }, medicinalUses: ["Digestive aid", "Anti-bacterial", "Stress relief"], ayurvedicBenefits: ["Supports digestion", "Reduces Kapha"], doshaEffect: "Balances Kapha", partUsed: "Leaves" },
  { scientificName: "Azadirachta indica", localNames: { hindi: "Neem", sanskrit: "Nimba" }, medicinalUses: ["Blood purifier", "Anti-fungal", "Skin disease treatment", "Dental care"], ayurvedicBenefits: ["Detoxifies blood (Rakta Shodhana)", "Reduces Pitta & Kapha", "Antibacterial & antiviral"], doshaEffect: "Balances Pitta & Kapha", partUsed: "Leaves, bark, oil" },
  { scientificName: "Curcuma longa", localNames: { hindi: "Haldi", sanskrit: "Haridra" }, medicinalUses: ["Anti-inflammatory", "Wound healing", "Liver protection", "Joint pain relief"], ayurvedicBenefits: ["Purifies blood", "Balances all three doshas", "Enhances complexion (Varnya)", "Supports digestion"], doshaEffect: "Tridosha balancing", partUsed: "Rhizome" },
  { scientificName: "Withania somnifera", localNames: { hindi: "Ashwagandha", sanskrit: "Ashwagandha" }, medicinalUses: ["Stress & anxiety relief", "Strength builder", "Improves sleep", "Boosts immunity"], ayurvedicBenefits: ["Rasayana (rejuvenative)", "Balances Vata & Kapha", "Enhances Ojas (vitality)", "Adaptogenic"], doshaEffect: "Balances Vata & Kapha", partUsed: "Root" },
  { scientificName: "Aloe vera", localNames: { hindi: "Ghritkumari", sanskrit: "Kumari" }, medicinalUses: ["Skin healing", "Digestive aid", "Burns treatment", "Laxative"], ayurvedicBenefits: ["Pitta shamana (cooling)", "Supports liver health", "Rejuvenates skin", "Balances Pitta"], doshaEffect: "Balances Pitta", partUsed: "Leaf gel" },
  { scientificName: "Aloe barbadensis", localNames: { hindi: "Ghritkumari", sanskrit: "Kumari" }, medicinalUses: ["Skin healing", "Digestive aid", "Burns treatment"], ayurvedicBenefits: ["Pitta shamana (cooling)", "Rejuvenates skin"], doshaEffect: "Balances Pitta", partUsed: "Leaf gel" },
  { scientificName: "Emblica officinalis", localNames: { hindi: "Amla", sanskrit: "Amalaki" }, medicinalUses: ["Rich in Vitamin C", "Hair growth", "Digestive tonic", "Eye health"], ayurvedicBenefits: ["Tridosha balancing", "Rasayana (rejuvenative)", "Enhances digestion (Deepana)"], doshaEffect: "Tridosha balancing", partUsed: "Fruit" },
  { scientificName: "Phyllanthus emblica", localNames: { hindi: "Amla", sanskrit: "Amalaki" }, medicinalUses: ["Rich in Vitamin C", "Hair growth", "Immunity booster"], ayurvedicBenefits: ["Tridosha balancing", "Rasayana (rejuvenative)"], doshaEffect: "Tridosha balancing", partUsed: "Fruit" },
  { scientificName: "Tinospora cordifolia", localNames: { hindi: "Giloy", sanskrit: "Guduchi" }, medicinalUses: ["Fever treatment", "Immunity booster", "Liver detox", "Anti-diabetic"], ayurvedicBenefits: ["Rasayana", "Balances all three doshas", "Medhya (brain tonic)", "Jwarahara (fever reducer)"], doshaEffect: "Tridosha balancing", partUsed: "Stem" },
  { scientificName: "Centella asiatica", localNames: { hindi: "Brahmi / Gotu Kola", sanskrit: "Mandukparni" }, medicinalUses: ["Memory enhancer", "Wound healing", "Anxiety relief", "Skin rejuvenation"], ayurvedicBenefits: ["Medhya Rasayana (brain tonic)", "Balances Pitta & Vata", "Improves concentration"], doshaEffect: "Balances Pitta & Vata", partUsed: "Whole plant" },
  { scientificName: "Bacopa monnieri", localNames: { hindi: "Brahmi", sanskrit: "Brahmi" }, medicinalUses: ["Memory & cognition", "Anxiety reduction", "Epilepsy support", "Neuroprotective"], ayurvedicBenefits: ["Medhya Rasayana", "Balances Vata & Pitta", "Enhances intellect (Buddhi Vardhaka)"], doshaEffect: "Balances Vata & Pitta", partUsed: "Whole plant" },
  { scientificName: "Terminalia arjuna", localNames: { hindi: "Arjun", sanskrit: "Arjuna" }, medicinalUses: ["Heart health", "Blood pressure regulation", "Cholesterol management"], ayurvedicBenefits: ["Hridya (cardiac tonic)", "Balances Pitta & Kapha", "Strengthens heart muscles"], doshaEffect: "Balances Pitta & Kapha", partUsed: "Bark" },
  { scientificName: "Terminalia chebula", localNames: { hindi: "Harad", sanskrit: "Haritaki" }, medicinalUses: ["Constipation relief", "Digestive tonic", "Eye health"], ayurvedicBenefits: ["Tridosha balancing", "Rasayana", "Part of Triphala"], doshaEffect: "Tridosha balancing", partUsed: "Fruit" },
  { scientificName: "Terminalia bellirica", localNames: { hindi: "Baheda", sanskrit: "Vibhitaki" }, medicinalUses: ["Cough remedy", "Hair tonic", "Eye health"], ayurvedicBenefits: ["Balances Kapha", "Part of Triphala", "Respiratory support"], doshaEffect: "Balances Kapha", partUsed: "Fruit" },
  { scientificName: "Moringa oleifera", localNames: { hindi: "Sahjan / Drumstick", sanskrit: "Shigru" }, medicinalUses: ["Nutrient-dense superfood", "Anti-inflammatory", "Blood sugar control", "Joint pain relief"], ayurvedicBenefits: ["Balances Vata & Kapha", "Rich in antioxidants", "Supports bone health"], doshaEffect: "Balances Vata & Kapha", partUsed: "Leaves, pods, seeds" },
  { scientificName: "Zingiber officinale", localNames: { hindi: "Adrak", sanskrit: "Shunti" }, medicinalUses: ["Nausea relief", "Digestive aid", "Cold & cough remedy", "Anti-inflammatory"], ayurvedicBenefits: ["Deepana (digestive fire enhancer)", "Balances Vata & Kapha", "Universal medicine (Vishwabheshaj)"], doshaEffect: "Balances Vata & Kapha", partUsed: "Rhizome" },
  { scientificName: "Piper nigrum", localNames: { hindi: "Kali Mirch", sanskrit: "Maricha" }, medicinalUses: ["Digestive stimulant", "Respiratory relief", "Bioavailability enhancer"], ayurvedicBenefits: ["Deepana-Pachana", "Balances Kapha & Vata", "Part of Trikatu formula"], doshaEffect: "Balances Kapha & Vata", partUsed: "Fruit" },
  { scientificName: "Piper longum", localNames: { hindi: "Pipli", sanskrit: "Pippali" }, medicinalUses: ["Respiratory health", "Digestive aid", "Liver support"], ayurvedicBenefits: ["Rasayana", "Balances Vata & Kapha", "Part of Trikatu"], doshaEffect: "Balances Vata & Kapha", partUsed: "Fruit" },
  { scientificName: "Cinnamomum verum", localNames: { hindi: "Dalchini", sanskrit: "Twak" }, medicinalUses: ["Blood sugar control", "Digestive aid", "Anti-microbial", "Warming spice"], ayurvedicBenefits: ["Balances Vata & Kapha", "Deepana (stimulates digestion)", "Supports oral health"], doshaEffect: "Balances Vata & Kapha", partUsed: "Bark" },
  { scientificName: "Syzygium aromaticum", localNames: { hindi: "Laung", sanskrit: "Lavanga" }, medicinalUses: ["Toothache relief", "Digestive aid", "Anti-bacterial"], ayurvedicBenefits: ["Balances Kapha & Vata", "Freshens breath", "Analgesic"], doshaEffect: "Balances Kapha & Vata", partUsed: "Flower bud" },
  { scientificName: "Elettaria cardamomum", localNames: { hindi: "Elaichi", sanskrit: "Ela" }, medicinalUses: ["Digestive aid", "Oral freshener", "Respiratory support"], ayurvedicBenefits: ["Tridosha balancing", "Improves appetite", "Detoxifying"], doshaEffect: "Tridosha balancing", partUsed: "Seeds, pods" },
  { scientificName: "Santalum album", localNames: { hindi: "Chandan", sanskrit: "Chandana" }, medicinalUses: ["Cooling agent", "Skin care", "Urinary disorders", "Mental calmness"], ayurvedicBenefits: ["Pitta shamana (cooling)", "Enhances complexion", "Calms the mind"], doshaEffect: "Balances Pitta", partUsed: "Heartwood, oil" },
  { scientificName: "Glycyrrhiza glabra", localNames: { hindi: "Mulethi", sanskrit: "Yashtimadhu" }, medicinalUses: ["Sore throat remedy", "Ulcer treatment", "Cough suppressant", "Adrenal support"], ayurvedicBenefits: ["Balances Vata & Pitta", "Rasayana", "Soothes mucous membranes"], doshaEffect: "Balances Vata & Pitta", partUsed: "Root" },
  { scientificName: "Asparagus racemosus", localNames: { hindi: "Shatavari", sanskrit: "Shatavari" }, medicinalUses: ["Female reproductive health", "Lactation support", "Digestive tonic", "Immunity booster"], ayurvedicBenefits: ["Rasayana", "Balances Pitta & Vata", "Nourishes all tissues (Dhatus)"], doshaEffect: "Balances Pitta & Vata", partUsed: "Root" },
  { scientificName: "Commiphora mukul", localNames: { hindi: "Guggul", sanskrit: "Guggulu" }, medicinalUses: ["Cholesterol management", "Joint health", "Weight management", "Anti-inflammatory"], ayurvedicBenefits: ["Balances Vata & Kapha", "Detoxifying (Ama Pachana)", "Supports thyroid function"], doshaEffect: "Balances Vata & Kapha", partUsed: "Resin" },
  { scientificName: "Boswellia serrata", localNames: { hindi: "Salai Guggul", sanskrit: "Shallaki" }, medicinalUses: ["Joint pain & arthritis relief", "Anti-inflammatory", "Respiratory support"], ayurvedicBenefits: ["Balances Vata & Kapha", "Supports joint mobility", "Reduces swelling"], doshaEffect: "Balances Vata & Kapha", partUsed: "Resin" },
  { scientificName: "Trigonella foenum-graecum", localNames: { hindi: "Methi", sanskrit: "Methika" }, medicinalUses: ["Blood sugar control", "Lactation support", "Digestive aid", "Hair health"], ayurvedicBenefits: ["Balances Vata & Kapha", "Deepana (digestive fire)", "Rich in fiber & iron"], doshaEffect: "Balances Vata & Kapha", partUsed: "Seeds, leaves" },
  { scientificName: "Hibiscus rosa-sinensis", localNames: { hindi: "Gudhal", sanskrit: "Japa" }, medicinalUses: ["Hair growth", "Blood pressure regulation", "Menstrual support"], ayurvedicBenefits: ["Balances Pitta", "Promotes hair health (Keshya)", "Cooling effect"], doshaEffect: "Balances Pitta", partUsed: "Flowers, leaves" },
  { scientificName: "Mentha arvensis", localNames: { hindi: "Pudina", sanskrit: "Pudina" }, medicinalUses: ["Digestive aid", "Headache relief", "Nausea remedy", "Cooling effect"], ayurvedicBenefits: ["Balances Pitta & Kapha", "Deepana (appetizer)", "Relieves gas & bloating"], doshaEffect: "Balances Pitta & Kapha", partUsed: "Leaves" },
  { scientificName: "Mentha spicata", localNames: { hindi: "Pudina", sanskrit: "Pudina" }, medicinalUses: ["Digestive aid", "Cooling effect", "Oral freshener"], ayurvedicBenefits: ["Balances Pitta & Kapha", "Appetizer"], doshaEffect: "Balances Pitta & Kapha", partUsed: "Leaves" },
  { scientificName: "Aegle marmelos", localNames: { hindi: "Bael", sanskrit: "Bilva" }, medicinalUses: ["Diarrhea treatment", "Digestive disorders", "Diabetes management"], ayurvedicBenefits: ["Tridosha balancing", "Sacred in Ayurveda", "Grahi (absorbent)"], doshaEffect: "Tridosha balancing", partUsed: "Fruit, leaves" },
  { scientificName: "Lawsonia inermis", localNames: { hindi: "Mehndi / Henna", sanskrit: "Madayantika" }, medicinalUses: ["Hair coloring & conditioning", "Cooling agent", "Skin healing", "Anti-fungal"], ayurvedicBenefits: ["Balances Pitta", "Natural hair dye", "Wound healing"], doshaEffect: "Balances Pitta", partUsed: "Leaves" },
  { scientificName: "Catharanthus roseus", localNames: { hindi: "Sadabahar", sanskrit: "Nityakalyani" }, medicinalUses: ["Diabetes management", "Anti-cancer properties", "Blood pressure regulation"], ayurvedicBenefits: ["Balances Kapha", "Supports blood sugar control", "Wound healing"], doshaEffect: "Balances Kapha", partUsed: "Leaves, flowers" },
  { scientificName: "Calendula officinalis", localNames: { hindi: "Genda", sanskrit: "Sthulapushpa" }, medicinalUses: ["Wound healing", "Skin inflammation", "Anti-fungal"], ayurvedicBenefits: ["Balances Pitta & Kapha", "Skin rejuvenation", "Anti-inflammatory"], doshaEffect: "Balances Pitta & Kapha", partUsed: "Flowers" },
  { scientificName: "Carica papaya", localNames: { hindi: "Papita", sanskrit: "Erandakarkati" }, medicinalUses: ["Digestive enzyme (papain)", "Dengue platelet support", "Skin health"], ayurvedicBenefits: ["Balances Vata & Kapha", "Deepana (digestive aid)", "Krimighna (anti-parasitic)"], doshaEffect: "Balances Vata & Kapha", partUsed: "Fruit, leaves" },
  { scientificName: "Mangifera indica", localNames: { hindi: "Aam", sanskrit: "Amra" }, medicinalUses: ["Rich in vitamins A & C", "Digestive aid (raw)", "Immunity booster"], ayurvedicBenefits: ["Ripe mango balances Vata", "Enhances complexion", "Nourishing (Brimhana)"], doshaEffect: "Ripe: Vata balancing", partUsed: "Fruit, leaves, bark" },
  { scientificName: "Ficus religiosa", localNames: { hindi: "Peepal", sanskrit: "Ashvattha" }, medicinalUses: ["Asthma relief", "Wound healing", "Diabetes support", "Dental care"], ayurvedicBenefits: ["Tridosha balancing", "Sacred tree in Ayurveda", "Skin disease treatment"], doshaEffect: "Tridosha balancing", partUsed: "Bark, leaves, fruit" },
  { scientificName: "Ficus benghalensis", localNames: { hindi: "Bargad / Banyan", sanskrit: "Vata" }, medicinalUses: ["Diarrhea treatment", "Dental care", "Skin ulcers"], ayurvedicBenefits: ["Balances Pitta & Kapha", "Grahi (absorbent)", "Wound healing"], doshaEffect: "Balances Pitta & Kapha", partUsed: "Bark, aerial roots" },
  { scientificName: "Murraya koenigii", localNames: { hindi: "Kadi Patta / Curry Leaf", sanskrit: "Surabhinimba" }, medicinalUses: ["Hair health", "Digestive aid", "Anti-diabetic", "Anti-oxidant"], ayurvedicBenefits: ["Balances Vata & Kapha", "Deepana", "Supports eye health"], doshaEffect: "Balances Vata & Kapha", partUsed: "Leaves" },
  { scientificName: "Bergera koenigii", localNames: { hindi: "Kadi Patta / Curry Leaf", sanskrit: "Surabhinimba" }, medicinalUses: ["Hair health", "Digestive aid", "Anti-diabetic"], ayurvedicBenefits: ["Balances Vata & Kapha", "Deepana"], doshaEffect: "Balances Vata & Kapha", partUsed: "Leaves" },
  { scientificName: "Coriandrum sativum", localNames: { hindi: "Dhaniya", sanskrit: "Dhanyaka" }, medicinalUses: ["Digestive aid", "Cooling agent", "Detoxification", "Urinary health"], ayurvedicBenefits: ["Tridosha balancing", "Deepana-Pachana", "Pitta shamana"], doshaEffect: "Tridosha balancing", partUsed: "Leaves, seeds" },
  { scientificName: "Cuminum cyminum", localNames: { hindi: "Jeera", sanskrit: "Jiraka" }, medicinalUses: ["Digestive stimulant", "Gas & bloating relief", "Iron-rich"], ayurvedicBenefits: ["Balances Vata & Kapha", "Deepana-Pachana", "Improves appetite"], doshaEffect: "Balances Vata & Kapha", partUsed: "Seeds" },
  { scientificName: "Ricinus communis", localNames: { hindi: "Arandi", sanskrit: "Eranda" }, medicinalUses: ["Constipation relief (castor oil)", "Joint pain", "Skin care"], ayurvedicBenefits: ["Balances Vata", "Virechana (purgative)", "Pain relief (Vedanasthapana)"], doshaEffect: "Balances Vata", partUsed: "Seeds (oil), root, leaves" },
  { scientificName: "Rosa damascena", localNames: { hindi: "Gulab", sanskrit: "Shatapatra" }, medicinalUses: ["Skin care", "Cooling agent", "Eye wash", "Mood enhancer"], ayurvedicBenefits: ["Balances Pitta", "Enhances complexion (Varnya)", "Calming & soothing"], doshaEffect: "Balances Pitta", partUsed: "Petals" },
  { scientificName: "Vetiveria zizanioides", localNames: { hindi: "Khas / Vetiver", sanskrit: "Ushira" }, medicinalUses: ["Cooling agent", "Skin disorders", "Fever reduction"], ayurvedicBenefits: ["Pitta shamana", "Dahatshamaka (burning sensation relief)", "Fragrant & calming"], doshaEffect: "Balances Pitta", partUsed: "Root" },
  { scientificName: "Chrysopogon zizanioides", localNames: { hindi: "Khas / Vetiver", sanskrit: "Ushira" }, medicinalUses: ["Cooling agent", "Skin disorders", "Fever reduction"], ayurvedicBenefits: ["Pitta shamana", "Calming"], doshaEffect: "Balances Pitta", partUsed: "Root" },
  { scientificName: "Nardostachys jatamansi", localNames: { hindi: "Jatamansi", sanskrit: "Jatamansi" }, medicinalUses: ["Sleep aid", "Anxiety relief", "Memory enhancer", "Skin health"], ayurvedicBenefits: ["Medhya (brain tonic)", "Balances Tridosha", "Nidrajanana (sleep inducer)"], doshaEffect: "Tridosha balancing", partUsed: "Rhizome" },
  { scientificName: "Convolvulus pluricaulis", localNames: { hindi: "Shankhpushpi", sanskrit: "Shankhpushpi" }, medicinalUses: ["Memory & concentration", "Anxiety & stress relief", "Sleep improvement"], ayurvedicBenefits: ["Medhya Rasayana", "Balances Pitta & Vata", "Brain tonic"], doshaEffect: "Balances Pitta & Vata", partUsed: "Whole plant" },
  { scientificName: "Eclipta prostrata", localNames: { hindi: "Bhringraj", sanskrit: "Bhringaraja" }, medicinalUses: ["Hair growth & health", "Liver support", "Skin disorders"], ayurvedicBenefits: ["Keshya (hair tonic)", "Balances Vata & Kapha", "Rasayana"], doshaEffect: "Balances Vata & Kapha", partUsed: "Whole plant" },
  { scientificName: "Mucuna pruriens", localNames: { hindi: "Kaunch Beej", sanskrit: "Kapikacchu" }, medicinalUses: ["Nervous system support", "Male fertility", "Mood enhancement", "Parkinson's support"], ayurvedicBenefits: ["Vrishya (aphrodisiac)", "Balances Vata", "Balya (strength giving)"], doshaEffect: "Balances Vata", partUsed: "Seeds" },
  { scientificName: "Trachyspermum ammi", localNames: { hindi: "Ajwain", sanskrit: "Yavani" }, medicinalUses: ["Gas & bloating relief", "Digestive aid", "Cold & cough"], ayurvedicBenefits: ["Balances Vata & Kapha", "Deepana-Pachana", "Relieves colic"], doshaEffect: "Balances Vata & Kapha", partUsed: "Seeds" },
];

/**
 * Look up Ayurvedic info by scientific name (fuzzy match).
 */
export function lookupAyurvedicInfo(scientificName: string): AyurvedicInfo | null {
  const query = scientificName.toLowerCase().trim();
  // Exact match first
  const exact = DB.find((p) => p.scientificName.toLowerCase() === query);
  if (exact) return exact;
  // Genus-level match (first word)
  const genus = query.split(" ")[0];
  const genusMatch = DB.find((p) => p.scientificName.toLowerCase().startsWith(genus));
  return genusMatch ?? null;
}
